
title: Talking Football
email: vv_softuni@abv.bg
description: >- # this means to ignore newlines until "baseurl:"
  It`s all about football !
baseurl: "/talking-football" 
url: "" # the base hostname & protocol for your site, e.g. http://example.com
destination: "docs"
github_username:  vVeskov

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed

exclude:
 - Gemfile
 - Gemfile.lock
 - node_modules
 - .gitignore
 - scss
 - gulpfile.js
 - package.json
 - package-lock.json
 - .vscode